export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  images: string[];
  sizes: string[];
  colors: string[];
  isNew: boolean;
  isBestseller: boolean;
}

export const products: Product[] = [
  {
    id: "dw-001",
    name: "Midnight Oversized Tee",
    category: "T-Shirts",
    price: 89,
    images: ["/images/products/midnight-tee-1.jpg", "/images/products/midnight-tee-2.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Obsidian", "Bone", "Charcoal"],
    isNew: true,
    isBestseller: false,
  },
  {
    id: "dw-002",
    name: "Essential Cargo Pants",
    category: "Pants",
    price: 145,
    images: ["/images/products/cargo-pants-1.jpg", "/images/products/cargo-pants-2.jpg"],
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Black", "Olive", "Sand"],
    isNew: false,
    isBestseller: true,
  },
  {
    id: "dw-003",
    name: "Drift Logo Hoodie",
    category: "Hoodies",
    price: 175,
    images: ["/images/products/logo-hoodie-1.jpg", "/images/products/logo-hoodie-2.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Washed Black", "Cream", "Slate"],
    isNew: false,
    isBestseller: true,
  },
  {
    id: "dw-004",
    name: "Structured Track Jacket",
    category: "Jackets",
    price: 220,
    images: ["/images/products/track-jacket-1.jpg", "/images/products/track-jacket-2.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Jet Black", "Stone"],
    isNew: true,
    isBestseller: false,
  },
  {
    id: "dw-005",
    name: "Washed Crewneck Sweatshirt",
    category: "Sweatshirts",
    price: 135,
    images: ["/images/products/crewneck-1.jpg", "/images/products/crewneck-2.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Vintage Black", "Fog", "Mocha"],
    isNew: false,
    isBestseller: false,
  },
  {
    id: "dw-006",
    name: "Relaxed Linen Shirt",
    category: "Shirts",
    price: 160,
    images: ["/images/products/linen-shirt-1.jpg", "/images/products/linen-shirt-2.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Ecru", "Charcoal", "Sage"],
    isNew: true,
    isBestseller: false,
  },
  {
    id: "dw-007",
    name: "Heavy Cotton Shorts",
    category: "Shorts",
    price: 95,
    images: ["/images/products/cotton-shorts-1.jpg", "/images/products/cotton-shorts-2.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Cement", "Navy"],
    isNew: false,
    isBestseller: true,
  },
  {
    id: "dw-008",
    name: "Drift Embossed Cap",
    category: "Accessories",
    price: 55,
    images: ["/images/products/cap-1.jpg", "/images/products/cap-2.jpg"],
    sizes: ["One Size"],
    colors: ["Black", "Off-White", "Olive"],
    isNew: false,
    isBestseller: true,
  },
  {
    id: "dw-009",
    name: "Oversized Bomber Jacket",
    category: "Jackets",
    price: 290,
    images: ["/images/products/bomber-1.jpg", "/images/products/bomber-2.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Matte Black", "Deep Forest"],
    isNew: true,
    isBestseller: false,
  },
  {
    id: "dw-010",
    name: "Tapered Sweatpants",
    category: "Pants",
    price: 125,
    images: ["/images/products/sweatpants-1.jpg", "/images/products/sweatpants-2.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Heather Black", "Oatmeal", "Ash"],
    isNew: false,
    isBestseller: false,
  },
  {
    id: "dw-011",
    name: "Raw Hem Tank Top",
    category: "T-Shirts",
    price: 65,
    images: ["/images/products/tank-top-1.jpg", "/images/products/tank-top-2.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Washed White", "Carbon", "Sand"],
    isNew: true,
    isBestseller: false,
  },
  {
    id: "dw-012",
    name: "Leather Minimal Wallet",
    category: "Accessories",
    price: 85,
    images: ["/images/products/wallet-1.jpg", "/images/products/wallet-2.jpg"],
    sizes: ["One Size"],
    colors: ["Black", "Tan", "Dark Brown"],
    isNew: false,
    isBestseller: true,
  },
];
